#include <core/sys.h>
void NMI_Handler(void) { /* IRQHandler Entry of NMI_Handler */ Error_Handler();}
void MemManage_Handler(void) { /* IRQHandler Entry of MemManage_Handler */ Error_Handler();}
void BusFault_Handler(void) { /* IRQHandler Entry of BusFault_Handler */ Error_Handler();}
void UsageFault_Handler(void) { /* IRQHandler Entry of UsageFault_Handler */ Error_Handler();}
void DebugMon_Handler(void) { /* IRQHandler Entry of DebugMon_Handler */ Error_Handler();}
void WWDG_IRQHandler(void) { /* IRQHandler Entry of WWDG_IRQHandler */ Error_Handler();}
void PVD_IRQHandler(void) { /* IRQHandler Entry of PVD_IRQHandler */ Error_Handler();}
void TAMP_STAMP_IRQHandler(void) { /* IRQHandler Entry of TAMP_STAMP_IRQHandler */ Error_Handler();}
void RTC_WKUP_IRQHandler(void) { /* IRQHandler Entry of RTC_WKUP_IRQHandler */ Error_Handler();}
void FLASH_IRQHandler(void) { /* IRQHandler Entry of FLASH_IRQHandler */ Error_Handler();}
void RCC_IRQHandler(void) { /* IRQHandler Entry of RCC_IRQHandler */ Error_Handler();}
void EXTI0_IRQHandler(void) { /* IRQHandler Entry of EXTI0_IRQHandler */ Error_Handler();}
void EXTI1_IRQHandler(void) { /* IRQHandler Entry of EXTI1_IRQHandler */ Error_Handler();}
void EXTI2_IRQHandler(void) { /* IRQHandler Entry of EXTI2_IRQHandler */ Error_Handler();}
void EXTI4_IRQHandler(void) { /* IRQHandler Entry of EXTI4_IRQHandler */ Error_Handler();}
void DMA1_Stream0_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream0_IRQHandler */ Error_Handler();}
void DMA1_Stream1_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream1_IRQHandler */ Error_Handler();}
void DMA1_Stream2_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream2_IRQHandler */ Error_Handler();}
void DMA1_Stream3_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream3_IRQHandler */ Error_Handler();}
void DMA1_Stream4_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream4_IRQHandler */ Error_Handler();}
void DMA1_Stream5_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream5_IRQHandler */ Error_Handler();}
void DMA1_Stream6_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream6_IRQHandler */ Error_Handler();}
void ADC_IRQHandler(void) { /* IRQHandler Entry of ADC_IRQHandler */ Error_Handler();}
void CAN1_TX_IRQHandler(void) { /* IRQHandler Entry of CAN1_TX_IRQHandler */ Error_Handler();}
void CAN1_RX0_IRQHandler(void) { /* IRQHandler Entry of CAN1_RX0_IRQHandler */ Error_Handler();}
void CAN1_RX1_IRQHandler(void) { /* IRQHandler Entry of CAN1_RX1_IRQHandler */ Error_Handler();}
void CAN1_SCE_IRQHandler(void) { /* IRQHandler Entry of CAN1_SCE_IRQHandler */ Error_Handler();}
void EXTI9_5_IRQHandler(void) { /* IRQHandler Entry of EXTI9_5_IRQHandler */ Error_Handler();}
void TIM1_BRK_TIM9_IRQHandler(void) { /* IRQHandler Entry of TIM1_BRK_TIM9_IRQHandler */ Error_Handler();}
void TIM1_UP_TIM10_IRQHandler(void) { /* IRQHandler Entry of TIM1_UP_TIM10_IRQHandler */ Error_Handler();}
void TIM1_TRG_COM_TIM11_IRQHandler(void) { /* IRQHandler Entry of TIM1_TRG_COM_TIM11_IRQHandler */ Error_Handler();}
void TIM1_CC_IRQHandler(void) { /* IRQHandler Entry of TIM1_CC_IRQHandler */ Error_Handler();}
void TIM2_IRQHandler(void) { /* IRQHandler Entry of TIM2_IRQHandler */ Error_Handler();}
void TIM3_IRQHandler(void) { /* IRQHandler Entry of TIM3_IRQHandler */ Error_Handler();}
void TIM4_IRQHandler(void) { /* IRQHandler Entry of TIM4_IRQHandler */ Error_Handler();}
void I2C1_EV_IRQHandler(void) { /* IRQHandler Entry of I2C1_EV_IRQHandler */ Error_Handler();}
void I2C1_ER_IRQHandler(void) { /* IRQHandler Entry of I2C1_ER_IRQHandler */ Error_Handler();}
void I2C2_EV_IRQHandler(void) { /* IRQHandler Entry of I2C2_EV_IRQHandler */ Error_Handler();}
void I2C2_ER_IRQHandler(void) { /* IRQHandler Entry of I2C2_ER_IRQHandler */ Error_Handler();}
void SPI2_IRQHandler(void) { /* IRQHandler Entry of SPI2_IRQHandler */ Error_Handler();}
void USART1_IRQHandler(void) { /* IRQHandler Entry of USART1_IRQHandler */ Error_Handler();}
void USART2_IRQHandler(void) { /* IRQHandler Entry of USART2_IRQHandler */ Error_Handler();}
void USART3_IRQHandler(void) { /* IRQHandler Entry of USART3_IRQHandler */ Error_Handler();}
void EXTI15_10_IRQHandler(void) { /* IRQHandler Entry of EXTI15_10_IRQHandler */ Error_Handler();}
void RTC_Alarm_IRQHandler(void) { /* IRQHandler Entry of RTC_Alarm_IRQHandler */ Error_Handler();}
void OTG_FS_WKUP_IRQHandler(void) { /* IRQHandler Entry of OTG_FS_WKUP_IRQHandler */ Error_Handler();}
void TIM8_BRK_TIM12_IRQHandler(void) { /* IRQHandler Entry of TIM8_BRK_TIM12_IRQHandler */ Error_Handler();}
void TIM8_UP_TIM13_IRQHandler(void) { /* IRQHandler Entry of TIM8_UP_TIM13_IRQHandler */ Error_Handler();}
void TIM8_TRG_COM_TIM14_IRQHandler(void) { /* IRQHandler Entry of TIM8_TRG_COM_TIM14_IRQHandler */ Error_Handler();}
void TIM8_CC_IRQHandler(void) { /* IRQHandler Entry of TIM8_CC_IRQHandler */ Error_Handler();}
void DMA1_Stream7_IRQHandler(void) { /* IRQHandler Entry of DMA1_Stream7_IRQHandler */ Error_Handler();}
void FSMC_IRQHandler(void) { /* IRQHandler Entry of FSMC_IRQHandler */ Error_Handler();}
void SDIO_IRQHandler(void) { /* IRQHandler Entry of SDIO_IRQHandler */ Error_Handler();}
void TIM5_IRQHandler(void) { /* IRQHandler Entry of TIM5_IRQHandler */ Error_Handler();}
void SPI3_IRQHandler(void) { /* IRQHandler Entry of SPI3_IRQHandler */ Error_Handler();}
void UART4_IRQHandler(void) { /* IRQHandler Entry of UART4_IRQHandler */ Error_Handler();}
void UART5_IRQHandler(void) { /* IRQHandler Entry of UART5_IRQHandler */ Error_Handler();}
void TIM6_DAC_IRQHandler(void) { /* IRQHandler Entry of TIM6_DAC_IRQHandler */ Error_Handler();}
void TIM7_IRQHandler(void) { /* IRQHandler Entry of TIM7_IRQHandler */ Error_Handler();}
void DMA2_Stream0_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream0_IRQHandler */ Error_Handler();}
void DMA2_Stream1_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream1_IRQHandler */ Error_Handler();}
void DMA2_Stream2_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream2_IRQHandler */ Error_Handler();}
void DMA2_Stream3_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream3_IRQHandler */ Error_Handler();}
void DMA2_Stream4_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream4_IRQHandler */ Error_Handler();}
void CAN2_TX_IRQHandler(void) { /* IRQHandler Entry of CAN2_TX_IRQHandler */ Error_Handler();}
void CAN2_RX0_IRQHandler(void) { /* IRQHandler Entry of CAN2_RX0_IRQHandler */ Error_Handler();}
void CAN2_RX1_IRQHandler(void) { /* IRQHandler Entry of CAN2_RX1_IRQHandler */ Error_Handler();}
void CAN2_SCE_IRQHandler(void) { /* IRQHandler Entry of CAN2_SCE_IRQHandler */ Error_Handler();}
void OTG_FS_IRQHandler(void) { /* IRQHandler Entry of OTG_FS_IRQHandler */ Error_Handler();}
void DMA2_Stream5_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream5_IRQHandler */ Error_Handler();}
void DMA2_Stream6_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream6_IRQHandler */ Error_Handler();}
void DMA2_Stream7_IRQHandler(void) { /* IRQHandler Entry of DMA2_Stream7_IRQHandler */ Error_Handler();}
void USART6_IRQHandler(void) { /* IRQHandler Entry of USART6_IRQHandler */ Error_Handler();}
void I2C3_EV_IRQHandler(void) { /* IRQHandler Entry of I2C3_EV_IRQHandler */ Error_Handler();}
void I2C3_ER_IRQHandler(void) { /* IRQHandler Entry of I2C3_ER_IRQHandler */ Error_Handler();}
void OTG_HS_EP1_OUT_IRQHandler(void) { /* IRQHandler Entry of OTG_HS_EP1_OUT_IRQHandler */ Error_Handler();}
void OTG_HS_EP1_IN_IRQHandler(void) { /* IRQHandler Entry of OTG_HS_EP1_IN_IRQHandler */ Error_Handler();}
void OTG_HS_WKUP_IRQHandler(void) { /* IRQHandler Entry of OTG_HS_WKUP_IRQHandler */ Error_Handler();}
void OTG_HS_IRQHandler(void) { /* IRQHandler Entry of OTG_HS_IRQHandler */ Error_Handler();}
void HASH_RNG_IRQHandler(void) { /* IRQHandler Entry of HASH_RNG_IRQHandler */ Error_Handler();}
void FPU_IRQHandler(void) { /* IRQHandler Entry of FPU_IRQHandler */ Error_Handler();}
