__lib_path         := $(PROJECT_ROOT)/lib
__lib_files_list   := maths.c quaternion.c
__lib_include_path := include
CPPFLAGS += $(addprefix -I$(__lib_path)/,$(__lib_include_path))
SOURCE_FILES_LIST += $(addprefix $(__lib_path)/src/, $(__lib_files_list))
