#ifndef __BOARD_BSP_ATK_FLIGHT_F405RG_PERIPH_PINMUX_H__
#define __BOARD_BSP_ATK_FLIGHT_F405RG_PERIPH_PINMUX_H__

extern void pinmux_init(void);

#endif /* __BOARD_BSP_ATK_FLIGHT_F405RG_PERIPH_PINMUX_H__ */
